import Head from 'next/head';
import Header from '../components/header';
import BodyHomepage from '../components/Homepage/Body';
import Footer from '../components/Footer';
// import Navbar from '../components/Navbar/index'
export default function Home() {
  return (
    <div>
      <Head>
        <title>UNIMA - Universitas Negeri Manado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icons/logo.ico" />
      </Head>
      {/* <!-- HEADER --> */}
      <Header />
      <BodyHomepage />
      <Footer />
    </div>
  );
}
